[project]
name = "prediccion-vientos-skbo"
version = "0.1.0"
description = "Modelo predictivo local de viento para el Aeropuerto Internacional El Dorado (SKBO) usando series históricas METAR"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.2.0",
    "keras-tuner>=1.4.8",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "tensorflow>=2.21.0",
]
